### ISSUE TITLE
Labs FW Bug: Gopro 10 stuck on third video with "Disable LRV" parameter

### ISSUE THREAD

**Issue by temp-64GTX** [gopro/labs#89] opened 2022-09-16 06:13 UTC
Disable LRV is a great useful option, but for some reason it makes camera stuck at third video.

Here is detailed view of this bug happening:

https://youtu.be/K7Q-x9Y4H6Y

It happening with both permanent and non-permanent parameter.
It not happens with other parameter (like bitrate 150) but without "Disable LRV".

**Comment by dnewman-gpsw** [comment] 2022-09-16 17:10
I have confirmed this bug on HERO10 and HERO11 Labs.  

What is the reason you are using this hack? The original reason is not longer needed, as the BITR extension now only applies to the HEVC stream, and all the bit-rate enhancements now work fine with LRVs present.

**Comment by temp-64GTX** [comment] 2022-09-16 18:50
Reason?
LRV files is a garbage. It's junk. I don't need them. Nobody need them. They eats sd-card speed. They eats gopro processor speed and battery. They causing fragmentation. They making a mess in video directory. I need to delete that files every single time. It's annoying.
Do you know, how happy i was, when i discover this lab-firmware, which can disable that mess? After half of a year of using gopro 10 and cleaning lrv-garbage. It was a miracle.
What-what? Light proxy files? I don't need proxy files. I am using post-process gyro stabilization so that proxy files are useless.

**Comment by dnewman-gpsw** [comment] 2022-09-16 22:28
Mobile App users need them, which is why they are there.  I use !MPRXY=1, which places them in a subfolder, out of the way and easy to remove. So to get them out of the way, use !MPRXY=1.

**Comment by temp-64GTX** [comment] 2023-01-20 17:01
Any chance to see this bug fixed?

**Comment by dnewman-gpsw** [comment] 2023-01-20 18:41
It is fixed in the next HERO11 and Mini Labs FW (released in 4-6 weeks likely.) HERO10 doesn't have a Labs build scheduled, however I have confirmed that the same fix can work on HERO10..  Labs will get a refresh if HERO10 main line firmware sees another update beyond 1.50.

**Closed** 2024-05-04 15:24 UTC
