### ISSUE TITLE
LTC Not Working w/ Hero 12 & Media Mod

### ISSUE THREAD

**Issue by rmdeluca** [gopro/labs#846] opened 2024-04-05 18:20 UTC
Using Labs firmware 2.20.70. I've tried using both a MixPre-12 II and Rode Wireless Pro to generate the LTC, both sources are confirmed working with another camera.

Framerate on the GoPro is set to 30, and LTC source is 29.97DF, but no combination of frame rate settings on either device works. Media Mod is set to Line-In, but no other input setting works either.

GoPro shows constant audio level on the screen at green with either source. I've attached an audio file with LTC output from the Rhode (29.97DF). The Rhode outputs on both channels and is connected with a stereo 3.5mm cable. The MixPre is connected via BNC to TS 3.5mm cable.

[GX010081.m4a.zip](https://github.com/gopro/labs/files/14889308/GX010081.m4a.zip)

**Comment by dnewman-gpsw** [comment] 2024-04-05 19:08
Yes this is bug.  Newer firmware is trying to increase performance by disabling some processing when not used.  Unfortunately it removed LTC scanning at boot. If you read the audio level is re-enables it. 
![image](https://github.com/gopro/labs/assets/10856084/362c6475-c6b6-4724-a8dc-163d42188d32)

Scan 
![image](https://github.com/gopro/labs/assets/10856084/9c3156ae-2af9-481b-a7c5-1ad5810464bf)

**Comment by rmdeluca** [comment] 2024-04-05 19:34
Unfortunately, that doesn't seem to help. it just shows SPL:0dB, with the audio meter briefly appearing underneath it if I plug/unplug the 3.5mm cable.

**Comment by dnewman-gpsw** [comment] 2024-04-05 19:47
I have confirmed this does work.  As are seeing 0dB SPL that will be a problem. No ideas at the moment.
![image](https://github.com/gopro/labs/assets/10856084/f3fc2962-4430-4c39-bd66-a5dd03ae8589)

**Comment by rmdeluca** [comment] 2024-04-05 20:14
What timecode FPS are you using?

**Comment by dnewman-gpsw** [comment] 2024-04-05 20:16
Tentacle Sync was set to 23.976fps.

**Comment by rmdeluca** [comment] 2024-04-05 20:38
Even factory resetting and removing the media mod, the camera always shows SPL:0dB. There is something different about your camera vs. mine :/

**Comment by dnewman-gpsw** [comment] 2024-04-05 21:17
No, there shouldn't be a difference.  As soon as I plug in the Media Mod (alone) the SPL start updating.  Without MM it will be 0dB, unless I enable Voice Control.

**Comment by rmdeluca** [comment] 2024-04-05 21:29
My settings are:

Video: bit rate high, bit depth 10-bit, anti-flicker 60Hz. Log profile, 30FPS, HyperSmooth On, Linear Lens. Shutter Auto, WB Native, RAW off, Wind Off. Voice control: on.

Do we differ much?

**Comment by dnewman-gpsw** [comment] 2024-04-05 21:47
None.  Are you not getting SPL levels even without MM?  Running 2.20.70?

**Comment by rmdeluca** [comment] 2024-04-05 21:55
No SPL levels even without MM. Yes, on 2.20.70.

**Comment by dnewman-gpsw** [comment] 2024-04-05 22:03
Lets see what else is active.

Scan 
![image](https://github.com/gopro/labs/assets/10856084/33c0fdf9-6d6c-4b8b-a66a-0cebece88cf9)

The will screen grab the features active and save a JPG in MISC call GRAB-date-time.jpg.  Like:
![GRAB-20240405-150204a](https://github.com/gopro/labs/assets/10856084/7b5d5fb3-4abc-476b-9dcc-c543f85dfda3)

**Comment by rmdeluca** [comment] 2024-04-05 22:08
![GRAB-20240405-180717a](https://github.com/gopro/labs/assets/1108545/e968999b-88a8-4bbf-ae7b-9b9f56af1f6b)

**Comment by dnewman-gpsw** [comment] 2024-04-05 22:35
I found a camera that did it, all had the same version FW number, but something must be different. So the AUDS hack was insufficient.  run !MBOOT="!Lbt"!SAVEbt=$PMSG="$pdB SPL"!N!R
 
This will get the audio processing going.

**Comment by rmdeluca** [comment] 2024-04-05 22:55
Yep, that fixed it! Thank you very much for the help.

**Comment by rmdeluca** [comment] 2024-04-11 15:24
After more testing, this feature isn't really useful in its current state, even when it does work. Making minor setting changes in the camera breaks the script, requiring it to be re-applied. Then, the timing is off by several seconds when imported into Resolve. On the other hand, simply recording the LTC into the audio track and telling Resolve to apply the audio track as timecode results in a perfect sync.

Granted, this is not GoPro's target market, but a few things would make it better when working in larger productions using timecode. Maybe these could become Labs firmware capabilities?

1) Ability to record in stereo, where one channel is timecode, and the other is the built-in or Media Mod microphone. That gives us scratch audio and timecode
2) IF the Media Mod is capable of stereo mic or line-in, then the ability to record both channels to a stereo track
3) Ability to shutoff the mode select feature that is bound to the power button. This is a constant source of shot-ruining nuisance-trips
4) Ability to either disable or adjust the overheat protection threshold and/or be alerted when the heat level is getting close and/or display the current internal temperature

**Comment by RikshaDriver** [comment] 2024-09-20 20:30
I've come across this same issue on H11 where AUDS isn't working either. The boot script leaves ugly arefacts on screen and a persistently pulsing spl output on the top in addition to AUDS on the bottom.

Is there a fix for this?

**Comment by dnewman-gpsw** [comment] 2024-09-20 20:36
The fix just camera out first on HERO13, simply enable Read LTC with *RLTC=1.
This is due to HERO12 in about a month.
HERO11 maybe early 2025, or whenever the next main firmware update happens.

**Comment by dnewman-gpsw** [comment] 2024-11-13 23:04
*RLTC=1 is now support on HERO12 2.30.70

**Closed by dnewman-gpsw** 2024-11-13 23:04 UTC
