### ISSUE TITLE
GoPro 12 WiFi change

### ISSUE THREAD

**Issue by thomasadye1** [gopro/labs#595] opened 2023-10-14 16:45 UTC
When using GoPro labs QR code to turn Wi-Fi on or off the max ISO is changed to 100. The same QR code is including a command to change the max ISO to 400 but it still changes to 100. If I’m changing Wi-Fi, only, it will also change the color profile to vivid. 
Just noticed on my 9 the ISO changes, but not the color profile.

**Comment by dnewman-gpsw** [comment] 2023-10-16 15:49
It doesn't in my testing.  Please share the QR Code that does this.

**Comment by thomasadye1** [comment] 2023-10-16 17:26
On Oct 16, 2023, at 10:50 AM, David Newman ***@***.***> wrote:﻿
It doesn't in my testing.  Please share the QR Code that does this.

**Comment by thomasadye1** [comment] 2023-10-16 17:39
![IMG_3996](https://github.com/gopro/labs/assets/147938742/67324de7-086b-44ef-a923-42c4b46db98b)
![IMG_3997](https://github.com/gopro/labs/assets/147938742/4ce8745b-fa4d-495e-ae60-1d1153e96b63)

**Comment by dnewman-gpsw** [comment] 2023-10-16 17:46
You are putting text where there should only be valid commands.  Use "Preset Name" for this, only use correctly formatted Labs commands in the "Added Command" field.

**Comment by dnewman-gpsw** [comment] 2023-10-16 17:47
Please confirm and close the issue, this is not a bug (user error.)

**Comment by thomasadye1** [comment] 2023-10-16 17:56
Now I understand. It was my newbe mistake. Not a bug (user error).😊

**Closed** 2023-10-16 17:57 UTC
